package fox

import "testing"

func TestDisplayHandlerNameCompactsAnonymousFunction(t *testing.T) {
	got := displayHandlerName("github.com/surge-go/fox/example.main.func2")
	if got != "example.func2" {
		t.Fatalf("displayHandlerName() = %q, want example.func2", got)
	}
}

func TestJoinFileAndHandlerNameSkipsDuplicatePrefix(t *testing.T) {
	got := joinFileAndHandlerName("main", "main.func2")
	if got != "main.func2" {
		t.Fatalf("joinFileAndHandlerName() = %q, want main.func2", got)
	}
}

func TestDisplayHandlerNameTrimsBoundMethodSuffix(t *testing.T) {
	got := displayHandlerName("main.(*AppController).Ping-fm")
	if got != "main.(*AppController).Ping" {
		t.Fatalf("displayHandlerName() = %q, want main.(*AppController).Ping", got)
	}
}

func TestJoinFileAndHandlerNameSkipsAutogeneratedPrefix(t *testing.T) {
	got := joinFileAndHandlerName("<autogenerated>", "main.(*AppController).Ping")
	if got != "main.(*AppController).Ping" {
		t.Fatalf("joinFileAndHandlerName() = %q, want main.(*AppController).Ping", got)
	}
}
